# Generated by Django 5.0.6 on 2024-05-27 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPS_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_uid', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapPopup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=255)),
                ('plate_no', models.CharField(max_length=255)),
                ('gps_uid', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle.gps_id')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimecoords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('gps_uid', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle.gps_id')),
            ],
        ),
    ]
