# Generated by Django 5.0.6 on 2024-06-06 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gps_id', models.CharField(max_length=100)),
                ('first_coords', models.CharField(blank=True, max_length=100, null=True)),
                ('second_coords', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_covered', models.FloatField(blank=True, null=True)),
                ('expected_time_to_reach', models.FloatField(blank=True, null=True)),
                ('transcation_amount', models.FloatField(default=0.0)),
                ('scanned_datetime', models.DateTimeField(auto_now_add=True)),
                ('tracker', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_amount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
                ('last_transaction', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Transaction_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_amount', models.FloatField(default=0.0)),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('pickup_point_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_point_longitude', models.FloatField(blank=True, null=True)),
                ('drop_point_latitude', models.FloatField(blank=True, null=True)),
                ('drop_point_longitude', models.FloatField(blank=True, null=True)),
                ('distance_covered', models.FloatField(blank=True, null=True)),
                ('expected_time_to_reach', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
