# Generated by Django 5.0.6 on 2024-06-05 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gps_id', models.CharField(max_length=100)),
                ('first_coords', models.CharField(blank=True, max_length=100, null=True)),
                ('second_coords', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_covered', models.FloatField(blank=True, null=True)),
                ('transcation_amount', models.FloatField(default=0.0)),
                ('scanned_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
