# Generated by Django 5.0.6 on 2024-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_transaction_history',
            old_name='drop_point',
            new_name='drop_point_latitude',
        ),
        migrations.RenameField(
            model_name='user_transaction_history',
            old_name='pickup_point',
            new_name='drop_point_longitude',
        ),
        migrations.AddField(
            model_name='user_transaction_history',
            name='pickup_point_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_transaction_history',
            name='pickup_point_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
