# Generated by Django 5.0.6 on 2024-05-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0002_rename_drop_point_user_transaction_history_drop_point_latitude_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coords',
            new_name='RealTimecoords',
        ),
    ]
