# Generated by Django 5.0.6 on 2024-06-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0002_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanned',
            name='expected_time_to_reach',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
